#define DEBUG_PRINTF_YES printf
#define DEBUG_PRINTF_NO(...)

#define DEBUG_FLUSH_YES printf("\n")
#define DEBUG_FLUSH_NO fflush(stdout)

#define DEBUG_EXIT_YES exit(-1)

#ifdef DEBUG_ROM_INFO
#define DEBUG_ROM DEBUG_PRINTF_YES
#define DEBUG_EXIT_ROM DEBUG_EXIT_YES
#define DEBUG_YES
#else
#define DEBUG_ROM DEBUG_PRINTF_NO
#define DEBUG_EXIT_ROM
#endif

#ifdef DEBUG_ROMSYS_MATCHING
#define DEBUG_ROMSYS DEBUG_PRINTF_YES
#define DEBUG_EXIT_ROMSYS DEBUG_EXIT_YES
#define DEBUG_YES
#else
#define DEBUG_ROMSYS DEBUG_PRINTF_NO
#define DEBUG_EXIT_ROMSYS
#endif

#ifdef DEBUG_CRC_MATCHING
#define DEBUG_CRC DEBUG_PRINTF_YES
#define DEBUG_FLUSH_CRC DEBUG_FLUSH_YES
#define DEBUG_EXIT_CRC DEBUG_EXIT_YES
#define DEBUG_YES
#else
#define DEBUG_CRC DEBUG_PRINTF_NO
#define DEBUG_FLUSH_CRC DEBUG_FLUSH_NO
#define DEBUG_EXIT_CRC
#endif

#ifdef DEBUG_ROMSYS_PP_MATCHING
#define DEBUG_EXIT_ROMSYS_PP DEBUG_EXIT_YES
#define DEBUG_YES
#else
#define DEBUG_EXIT_ROMSYS_PP
#endif

#ifdef DEBUG_RSA_MATCHING
#define DEBUG_RSA DEBUG_PRINTF_YES
#define DEBUG_EXIT_RSA DEBUG_EXIT_YES
#define DEBUG_YES
#else
#define DEBUG_RSA DEBUG_PRINTF_NO
#define DEBUG_EXIT_RSA
#endif

#ifdef DEBUG_MAIN_MATCHING
#define DEBUG_MAIN DEBUG_PRINTF_YES
#define DEBUG_FLUSH_MAIN DEBUG_FLUSH_YES
#define DEBUG_EXIT_MAIN DEBUG_EXIT_YES
#define DEBUG_YES
#else
#define DEBUG_MAIN DEBUG_PRINTF_NO
#define DEBUG_FLUSH_MAIN DEBUG_FLUSH_NO
#define DEBUG_EXIT_MAIN
#endif

#ifdef DEBUG_MULTIPOINT_MATCHING
#define DEBUG_MULTIPOINT DEBUG_PRINTF_YES
#define DEBUG_FLUSH_MULTIPOINT DEBUG_FLUSH_YES
#define DEBUG_EXIT_MULTIPOINT DEBUG_EXIT_YES
#define DEBUG_YES
#else
#define DEBUG_MULTIPOINT DEBUG_PRINTF_NO
#define DEBUG_FLUSH_MULTIPOINT DEBUG_FLUSH_NO
#define DEBUG_EXIT_MULTIPOINT
#endif
