#!/bin/bash
for i in $*; do
    box=$( ../me7sum -s $i | grep "Part Number" | sed -e 's/ //g' | cut -f 2 -d \')
    ver=$( ../me7sum -s $i | grep "SW Version" | sed -e 's/ //g' | cut -f 2 -d \')
    ssecu=$( ../me7sum -s $i | grep "SW Number" | sed -e 's/^1037//' | sed -e 's/ //g' )

    if [ -z "$box" -o -z "$ver" -o -z "$ssecu" ]; then
	echo $i box=\"$box\" ver=\"$ver\" ssecu=\"$ssecu\" failed >&2
	continue
    fi

    outll=$box-$ver-$ssecu.bin
    outl=$box-$ver.bin
    out=$box.bin

    if [ "$i" = "$out" -o "$i" = "$outl" ]; then
	echo $i \($outl\) ok >&2
    else
	if [ ! -f "$out" ]; then
	    echo git mv $i $out
	elif [ ! -f "outl" ]; then
	    echo git mv $i $outl
	elif [ ! -f "outll" ]; then
	    echo git mv $i $outll
	else
	    echo $i $outll failed >&2
	fi
    fi
done
