#!/bin/bash
for i in $*; do
    box=$( ../me7sum -e $i | grep "Part Number" | cut -f 2 -d \')
    ver=$( strings $i | grep 0261 | sed -e 's/1037/-/' )

    [ -z "$box" ] && exit
    [ -z "$ver" ] && exit

    outl=$box-$ver.bin
    out=$box.bin

    if [ "$i" = "$out" -o "$i" = "$outl" ]; then
	echo $i \($outl\) ok
    else
	if [ ! -f "$out" ]; then
	    echo git mv $i $out
	elif [ ! -f "outl" ]; then
	    echo git mv $i $outl
	else
	    echo failed
	fi
    fi
done
